name: Build

on: [push]

jobs:

  test:
    name: Node Backend Tests
    strategy:
        matrix:
          version: [6, 10, 16]
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
    - run: npm ci
    - run: npm test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
